<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

use App\Models\Medicamento;

class MedicamentoSeeder extends Seeder
{

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Medicamento::factory()->count(200)->create();

        DB::table('medicamentos')->insert([
            [
                'referencia' => 1001,
                'nome' => 'Paracetamol',
                'preco' => 15.90,
                'descricao' => 'Analgésico e antitérmico para alívio de dores e febre',
                'forma' => 'Comprimido',
                'dosagem' => '750mg',
                'imagem' => 'medicine_images/paracetamol.jpg',
                'quantidade' => 100,
                'industria' => 'Medley',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1002,
                'nome' => 'Dipirona',
                'preco' => 12.50,
                'descricao' => 'Medicamento para dor e febre',
                'forma' => 'Comprimido',
                'dosagem' => '500mg',
                'imagem' => 'medicine_images/dipirona.png',
                'quantidade' => 80,
                'industria' => 'EMS',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1003,
                'nome' => 'Amoxicilina',
                'preco' => 45.90,
                'descricao' => 'Antibiótico de amplo espectro',
                'forma' => 'Cápsula',
                'dosagem' => '500mg',
                'imagem' => 'medicine_images/amoxicilina.png',
                'quantidade' => 50,
                'industria' => 'Neo Química',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1004,
                'nome' => 'Omeprazol',
                'preco' => 25.80,
                'descricao' => 'Medicamento para problemas gástricos',
                'forma' => 'Cápsula',
                'dosagem' => '20mg',
                'imagem' => 'medicine_images/omeprazol.jpg',
                'quantidade' => 120,
                'industria' => 'Medley',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1005,
                'nome' => 'Ibuprofeno',
                'preco' => 18.75,
                'descricao' => 'Anti-inflamatório não esteroidal',
                'forma' => 'Comprimido',
                'dosagem' => '600mg',
                'imagem' => 'medicine_images/ibuprofeno.png',
                'quantidade' => 90,
                'industria' => 'Eurofarma',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1006,
                'nome' => 'Loratadina',
                'preco' => 22.90,
                'descricao' => 'Antialérgico de uso oral',
                'forma' => 'Comprimido',
                'dosagem' => '10mg',
                'imagem' => 'medicine_images/loratadina.jpg',
                'quantidade' => 75,
                'industria' => 'Neo Química',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1007,
                'nome' => 'Dexametasona',
                'preco' => 32.60,
                'descricao' => 'Corticosteroide para inflamações',
                'forma' => 'Creme',
                'dosagem' => '1mg/ml',
                'imagem' => 'medicine_images/dexametasona.png',
                'quantidade' => 60,
                'industria' => 'EMS',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1008,
                'nome' => 'Metformina',
                'preco' => 28.90,
                'descricao' => 'Medicamento para diabetes tipo 2',
                'forma' => 'Comprimido',
                'dosagem' => '850mg',
                'imagem' => 'medicine_images/metformina.png',
                'quantidade' => 110,
                'industria' => 'Medley',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1009,
                'nome' => 'Sertralina',
                'preco' => 55.75,
                'descricao' => 'Antidepressivo da classe ISRS',
                'forma' => 'Comprimido',
                'dosagem' => '50mg',
                'imagem' => 'medicine_images/sertralina.jpg',
                'quantidade' => 40,
                'industria' => 'Eurofarma',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1010,
                'nome' => 'Atenolol',
                'preco' => 19.90,
                'descricao' => 'Beta-bloqueador para hipertensão',
                'forma' => 'Comprimido',
                'dosagem' => '25mg',
                'imagem' => 'medicine_images/atenolol.jpg',
                'quantidade' => 95,
                'industria' => 'Neo Química',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1011,
                'nome' => 'Simeticona',
                'preco' => 16.50,
                'descricao' => 'Alívio de gases intestinais',
                'forma' => 'Comprimido',
                'dosagem' => '125mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 100,
                'industria' => 'EMS',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1012,
                'nome' => 'Losartana',
                'preco' => 23.40,
                'descricao' => 'Antagonista do receptor de angiotensina II para hipertensão',
                'forma' => 'Comprimido',
                'dosagem' => '50mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 85,
                'industria' => 'Neo Química',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1013,
                'nome' => 'Cetoconazol',
                'preco' => 29.90,
                'descricao' => 'Antifúngico para tratamento de micoses',
                'forma' => 'Creme',
                'dosagem' => '20mg/g',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 60,
                'industria' => 'Medley',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1014,
                'nome' => 'Ranitidina',
                'preco' => 27.80,
                'descricao' => 'Reduz a produção de ácido no estômago',
                'forma' => 'Comprimido',
                'dosagem' => '150mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 75,
                'industria' => 'EMS',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1015,
                'nome' => 'Azitromicina',
                'preco' => 48.50,
                'descricao' => 'Antibiótico para infecções bacterianas',
                'forma' => 'Comprimido',
                'dosagem' => '500mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 50,
                'industria' => 'Eurofarma',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1016,
                'nome' => 'Fluconazol',
                'preco' => 36.20,
                'descricao' => 'Antifúngico para infecções fúngicas',
                'forma' => 'Cápsula',
                'dosagem' => '150mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 45,
                'industria' => 'Neo Química',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1017,
                'nome' => 'Aspirina',
                'preco' => 10.50,
                'descricao' => 'Analgésico e anti-inflamatório',
                'forma' => 'Comprimido',
                'dosagem' => '500mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 200,
                'industria' => 'Bayer',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1018,
                'nome' => 'Levotiroxina',
                'preco' => 24.80,
                'descricao' => 'Hormônio tireoidiano sintético',
                'forma' => 'Comprimido',
                'dosagem' => '50mcg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 100,
                'industria' => 'Sanofi',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1019,
                'nome' => 'Cloridrato de Sertralina',
                'preco' => 60.75,
                'descricao' => 'Antidepressivo para tratamento de depressão e ansiedade',
                'forma' => 'Comprimido',
                'dosagem' => '100mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 30,
                'industria' => 'Medley',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1020,
                'nome' => 'Alprazolam',
                'preco' => 50.30,
                'descricao' => 'Ansiolítico para transtornos de ansiedade',
                'forma' => 'Comprimido',
                'dosagem' => '1mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 50,
                'industria' => 'Pfizer',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1021,
                'nome' => 'Clonazepam',
                'preco' => 38.50,
                'descricao' => 'Ansiolítico para transtornos de pânico e ansiedade',
                'forma' => 'Comprimido',
                'dosagem' => '2mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 60,
                'industria' => 'Genéricos',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1022,
                'nome' => 'Bromoprida',
                'preco' => 15.20,
                'descricao' => 'Antiemético para náuseas e vômitos',
                'forma' => 'Comprimido',
                'dosagem' => '10mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 50,
                'industria' => 'Neo Química',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1023,
                'nome' => 'Prednisona',
                'preco' => 30.00,
                'descricao' => 'Corticosteroide para tratamento de inflamações',
                'forma' => 'Comprimido',
                'dosagem' => '20mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 40,
                'industria' => 'EMS',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1024,
                'nome' => 'Cloridrato de Ciprofloxacino',
                'preco' => 58.90,
                'descricao' => 'Antibiótico para infecções bacterianas',
                'forma' => 'Comprimido',
                'dosagem' => '500mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 30,
                'industria' => 'Medley',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1025,
                'nome' => 'Carbamazepina',
                'preco' => 44.50,
                'descricao' => 'Antiepilético e estabilizador de humor',
                'forma' => 'Comprimido',
                'dosagem' => '200mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 90,
                'industria' => 'Eurofarma',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1026,
                'nome' => 'Hidroclorotiazida',
                'preco' => 12.90,
                'descricao' => 'Diurético para controle de pressão arterial',
                'forma' => 'Comprimido',
                'dosagem' => '25mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 120,
                'industria' => 'Sanofi',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1027,
                'nome' => 'Cetirizina',
                'preco' => 17.90,
                'descricao' => 'Antialérgico para alívio de sintomas de alergia',
                'forma' => 'Comprimido',
                'dosagem' => '10mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 50,
                'industria' => 'Neo Química',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1028,
                'nome' => 'Furosemida',
                'preco' => 20.30,
                'descricao' => 'Diurético para retenção de líquidos',
                'forma' => 'Comprimido',
                'dosagem' => '40mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 80,
                'industria' => 'EMS',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1029,
                'nome' => 'Lorazepam',
                'preco' => 45.90,
                'descricao' => 'Ansiolítico e sedativo para transtornos de ansiedade',
                'forma' => 'Comprimido',
                'dosagem' => '2mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 30,
                'industria' => 'Pfizer',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1030,
                'nome' => 'Captopril',
                'preco' => 14.90,
                'descricao' => 'Inibidor da ECA para controle de hipertensão',
                'forma' => 'Comprimido',
                'dosagem' => '25mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 100,
                'industria' => 'Medley',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1031,
                'nome' => 'Enalapril',
                'preco' => 21.50,
                'descricao' => 'Inibidor da ECA para controle da pressão arterial',
                'forma' => 'Comprimido',
                'dosagem' => '10mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 60,
                'industria' => 'EMS',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1032,
                'nome' => 'Aciclovir',
                'preco' => 28.40,
                'descricao' => 'Antiviral para tratamento de herpes',
                'forma' => 'Creme',
                'dosagem' => '50mg/g',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 30,
                'industria' => 'Neo Química',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1033,
                'nome' => 'Gliclazida',
                'preco' => 33.80,
                'descricao' => 'Antidiabético oral para controle de glicemia',
                'forma' => 'Comprimido',
                'dosagem' => '60mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 50,
                'industria' => 'Eurofarma',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1034,
                'nome' => 'Espironolactona',
                'preco' => 19.30,
                'descricao' => 'Diurético poupador de potássio',
                'forma' => 'Comprimido',
                'dosagem' => '25mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 70,
                'industria' => 'Sanofi',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1035,
                'nome' => 'Diclofenaco',
                'preco' => 22.10,
                'descricao' => 'Anti-inflamatório e analgésico',
                'forma' => 'Comprimido',
                'dosagem' => '50mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 90,
                'industria' => 'EMS',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1036,
                'nome' => 'Clindamicina',
                'preco' => 46.00,
                'descricao' => 'Antibiótico para infecções bacterianas graves',
                'forma' => 'Cápsula',
                'dosagem' => '300mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 50,
                'industria' => 'Pfizer',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1037,
                'nome' => 'Pantoprazol',
                'preco' => 25.00,
                'descricao' => 'Inibidor de bomba de prótons para problemas gástricos',
                'forma' => 'Comprimido',
                'dosagem' => '40mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 100,
                'industria' => 'Medley',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1038,
                'nome' => 'Alendronato',
                'preco' => 55.30,
                'descricao' => 'Tratamento para osteoporose',
                'forma' => 'Comprimido',
                'dosagem' => '70mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 30,
                'industria' => 'EMS',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1039,
                'nome' => 'Sinvastatina',
                'preco' => 18.50,
                'descricao' => 'Redutor de colesterol e lipídios no sangue',
                'forma' => 'Comprimido',
                'dosagem' => '20mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 90,
                'industria' => 'Eurofarma',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'referencia' => 1040,
                'nome' => 'Risperidona',
                'preco' => 61.40,
                'descricao' => 'Antipsicótico para transtornos mentais',
                'forma' => 'Comprimido',
                'dosagem' => '1mg',
                'imagem' => 'medicine-placeholder.svg',
                'quantidade' => 30,
                'industria' => 'Janssen',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }

}
